springdoc:
  api-docs.path:  mobile-services-doc

mobile:
  url:  https://run.mocky.io/v3/b755c334-9627-4b09-84f2-548cb1918184
  connectionTimeout:  10000
spring:
  application:
    name: MOBILE-SERVICES
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://myeureka-server.herokuapp.com/eureka